# <font color=1BBC00> Natural Language Processing with Machine Learning methods. </font>

<i><u>by</u></i>
<br><i> Agit Çelik</i>

# ***

<font color=CC0000> <b> DATASET: Amazon Product Reviews </b> </font> <b> -> </b> determine the <u>Rating</u> (target), given comments.

*Credit: https://www.kaggle.com/datafiniti/consumer-reviews-of-amazon-products

In [1]:
#Required imports
import pandas as pd
import numpy as np

import seaborn as sns

%matplotlib inline
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('amazon_product_reviews-simplified.csv', delimiter=';') #read the data

### <font color=00A99C> Exploratory Analysis </font>

In [3]:
df.shape

(34660, 2)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34660 entries, 0 to 34659
Data columns (total 2 columns):
reviews_text      34659 non-null object
reviews_rating    34627 non-null float64
dtypes: float64(1), object(1)
memory usage: 541.6+ KB


In [5]:
df.describe()

reviews_rating
count    34627.000000
mean         4.584573
std          0.735653
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000

In [6]:
df.head()

reviews_text  reviews_rating
0  This product so far has not disappointed. My c...             5.0
1  great for beginner or experienced person. Boug...             5.0
2  Inexpensive tablet for him to use and learn on...             5.0
3  I've had my Fire HD 8 two weeks now and I love...             4.0
4  I bought this for my grand daughter when she c...             5.0

In [7]:
df.tail()

reviews_text  reviews_rating
34655  This is not appreciably faster than any other ...             3.0
34656  Amazon should include this charger with the Ki...             1.0
34657  Love my Kindle Fire but I am really disappoint...             1.0
34658  I was surprised to find it did not come with a...             1.0
34659  to spite the fact that i have nothing but good...             1.0

### <font color=00A99C> Preprocess </font>

In [8]:
X = df['reviews_text'] #Seperate the comments

In [9]:
y = df['reviews_rating'] #Seperate the ratings
y

0        5.0
1        5.0
2        5.0
3        4.0
4        5.0
5        5.0
6        4.0
7        5.0
8        5.0
9        5.0
10       4.0
11       5.0
12       4.0
13       5.0
14       5.0
15       5.0
16       4.0
17       4.0
18       5.0
19       5.0
20       5.0
21       5.0
22       5.0
23       5.0
24       5.0
25       4.0
26       4.0
27       5.0
28       5.0
29       5.0
        ... 
34630    4.0
34631    1.0
34632    5.0
34633    1.0
34634    5.0
34635    5.0
34636    5.0
34637    1.0
34638    3.0
34639    5.0
34640    5.0
34641    4.0
34642    5.0
34643    5.0
34644    5.0
34645    5.0
34646    5.0
34647    5.0
34648    5.0
34649    5.0
34650    2.0
34651    5.0
34652    1.0
34653    1.0
34654    1.0
34655    3.0
34656    1.0
34657    1.0
34658    1.0
34659    1.0
Name: reviews_rating, Length: 34660, dtype: float64

In [10]:
import math
oldY = y
yList=[]

for element in oldY:
    print(element)
    if math.isnan(element):
        yList.append(1)
    elif not(np.isfinite(element)):
        yList.append(1)
    else:
        yList.append(element)
yList

5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
2.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
1.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
4.0
4.0
3.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
1.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0


5.0
5.0
4.0
5.0
5.0
5.0
1.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
1.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
3.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
3.0
5.0
5.0
5.0
1.0
4.0
3.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
1.0
5.0
5.0
4.0
4.0
5.0
5.0
1.0
5.0
5.0
3.0
5.0
3.0
5.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
2.0
1.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
4.0
1.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
1.0
5.0
5.0
4.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
2.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
5.0


4.0
2.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
3.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
2.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
3.0
4.0
5.0
4.0
4.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
1.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
3.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
3.0
4.0
4.0
5.0
4.0
4.0
4.0
3.0
4.0
3.0
4.0
5.0
5.0
3.0
5.0
4.0
2.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
3.0
4.0
4.0
5.0
3.0
4.0
5.0
5.0
5.0
4.0
3.0
5.0
4.0
2.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
3.0
5.0
5.0
5.0
5.0
4.0
5.0
1.0
5.0
4.0
5.0
3.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
3.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
3.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
1.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0


5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
1.0
4.0
5.0
5.0
5.0
2.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
2.0
3.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
2.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
1.0
4.0
4.0
5.0
4.0
3.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
1.0
5.0
5.0
5.0
4.0
1.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
3.0
5.0
5.0
4.0
4.0
1.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
4.0
4.0
4.0
5.0
4.0
4.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
2.0
4.0
5.0
3.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
2.0
4.0
4.0
3.0
2.0
5.0
3.0
5.0
4.0
3.0
5.0
2.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
4.0
4.0
5.0
3.0
5.0
5.0
4.0
5.0
1.0
5.0
4.0
5.0
5.0
4.0
4.0


4.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
1.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
3.0
5.0
3.0
4.0
3.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
1.0
2.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
4.0
4.0
4.0
4.0
3.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
3.0
5.0
4.0
4.0
5.0
4.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
3.0
5.0
5.0
3.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
1.0
4.0
5.0
3.0
5.0
3.0
5.0
3.0
3.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
3.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
3.0
4.0
4.0
2.0
4.0
4.0
5.0
5.0
5.0
3.0
4.0
4.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0


4.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
4.0
3.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
3.0
5.0
4.0
5.0
5.0
4.0
3.0
5.0
2.0
3.0
4.0
5.0
5.0
4.0
5.0
4.0
4.0
3.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
5.0
4.0
4.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
1.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
3.0
4.0
5.0
4.0
5.0
2.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
4.0
4.0
5.0
4.0
2.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
3.0
4.0
4.0
4.0
3.0
5.0
5.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
2.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
3.0
5.0
5.0
2.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
2.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
3.0
2.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0


5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
3.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
2.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
3.0
5.0
3.0
5.0
5.0
3.0
5.0
2.0
5.0
4.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0


4.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
3.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
4.0
3.0
5.0
3.0
1.0
4.0
5.0
4.0
2.0
4.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
2.0
5.0
5.0
1.0
5.0
5.0
4.0
5.0
3.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
2.0
3.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
1.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
1.0
5.0
4.0


5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
4.0
3.0
4.0
4.0
5.0
5.0
5.0
3.0
4.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
3.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
2.0
5.0
5.0
5.0
3.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
3.0
4.0
3.0
1.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
2.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
4.0
3.0
5.0
5.0
5.0
5.0
4.0
5.0
3.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0


4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
2.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
1.0
4.0
4.0
4.0
5.0
5.0
2.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
2.0
5.0
4.0
5.0
5.0
4.0
4.0
4.0
1.0
5.0
4.0
1.0
5.0
4.0
4.0
4.0
5.0
4.0
2.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
5.0
4.0
5.0
3.0
3.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
5.0
3.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
nan
5.0
4.0
5.0
5.0
4.0
4.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
3.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
4.0
3.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
4.0
5.0
5.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
2.0
3.0
5.0


5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
1.0
4.0
5.0
4.0
5.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
4.0
5.0
3.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
1.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
1.0
5.0
2.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
4.0
5.0
5.0
5.0
5.0
4.0
4.0
4.0
4.0
5.0
5.0
5.0
5.0
5.0
5.0
3.0
5.0
5.0
3.0
5.0
4.0
5.0


[5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 4.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 4.0,
 4.0,
 5.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 2.0,
 5.0,
 4.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 1.0,
 5.0,
 5.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0,
 5.0,
 4.0,
 5.0,
 4.0,
 4.0,
 5.0,
 5.0,
 4.0,
 5.0,
 4.0,
 4.0,
 5.0,
 4.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 5.0,
 4.0,
 4.0

In [11]:
len(yList)

34660

In [12]:
y = pd.Series(yList)

In [13]:
type(y)

pandas.core.series.Series

In [14]:
X.head()

0    This product so far has not disappointed. My c...
1    great for beginner or experienced person. Boug...
2    Inexpensive tablet for him to use and learn on...
3    I've had my Fire HD 8 two weeks now and I love...
4    I bought this for my grand daughter when she c...
Name: reviews_text, dtype: object

In [15]:
y.head()

0    5.0
1    5.0
2    5.0
3    4.0
4    5.0
dtype: float64

In [16]:
# *** Preprocess the Features

import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# -> TOKENIZATION with PUNCUTATION REMOVAL
tokenizedReviewsTextList = list()
tokenizer = RegexpTokenizer(r'\w+')

for review in X.values.astype('U'):
    tokenizedReviewsTextList.append(tokenizer.tokenize(review))

# -> STOPWORDS REMOVAL
stop_words = set(stopwords.words('english'))

currentFilteredTokenizedReviewsTextList = list()
filteredTokenizedReviewsTextList = list()

# Nested for -- because of the fact that filteredTokenizedReviewsTextList is array of arrays:
for review in tokenizedReviewsTextList:
    for tokenizedWord in review:
        tokenizedWord = tokenizedWord.lower()
        if tokenizedWord not in stop_words:
            currentFilteredTokenizedReviewsTextList.append(tokenizedWord)

    # Keep the data into filteredTokenizedReviewsTextList, for further purposes
    filteredTokenizedReviewsTextList.append(currentFilteredTokenizedReviewsTextList.copy())

    currentFilteredTokenizedReviewsTextList.clear()

# -> Porter Stemmer:
ps = PorterStemmer()

currentPStemmedFilteredTokenizedReviewsTextList = list()
pStemmedFilteredTokenizedReviewsTextList = list()

for review in filteredTokenizedReviewsTextList:
    for filteredTokenizedWord in review:
        filteredTokenizedWord = ps.stem(filteredTokenizedWord)
        currentPStemmedFilteredTokenizedReviewsTextList.append(filteredTokenizedWord)

    pStemmedFilteredTokenizedReviewsTextList.append(
        currentPStemmedFilteredTokenizedReviewsTextList.copy())

    currentPStemmedFilteredTokenizedReviewsTextList.clear()

In [17]:
# -> Obtain the requested text_data for creation of the Bag-of-Words
text_data = []
review_sentences = ""
for review in pStemmedFilteredTokenizedReviewsTextList:
    for word in review:
        review_sentences = review_sentences +word +" "
    text_data.append(review_sentences)
    review_sentences = ""

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

# Create the bag of words feature matrix
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

# Show feature matrix
bag_of_words.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
# Get feature names
feature_names = count.get_feature_names()

# View feature names
feature_names

['00',
 '000',
 '01',
 '04',
 '05',
 '06',
 '0ff',
 '0ghz',
 '0ne',
 '10',
 '100',
 '1000',
 '1000ma',
 '1005',
 '100m',
 '100mbp',
 '100x',
 '1024',
 '1024x600',
 '105',
 '107',
 '108',
 '1080',
 '1080p',
 '10and',
 '10in',
 '10it',
 '10k',
 '10t',
 '10th',
 '10w',
 '10x',
 '10yr',
 '11',
 '110',
 '119',
 '11yr',
 '12',
 '120',
 '1200',
 '120v',
 '122',
 '123',
 '125',
 '1275',
 '128',
 '1280',
 '128gb',
 '129',
 '1292',
 '1299',
 '12gb',
 '12hr',
 '12mpb',
 '12th',
 '12yr',
 '13',
 '130',
 '139',
 '13th',
 '13yr',
 '14',
 '140',
 '1400',
 '149',
 '14yo',
 '14yr',
 '15',
 '150',
 '1500',
 '159',
 '15mbp',
 '15min',
 '15yr',
 '16',
 '160',
 '165',
 '16g',
 '16gb',
 '16love',
 '16th',
 '16yr',
 '17',
 '179',
 '17th',
 '18',
 '180',
 '1800',
 '18000',
 '182',
 '185',
 '189ppi',
 '19',
 '190',
 '191',
 '194',
 '1958',
 '1960',
 '1969',
 '1980',
 '1984',
 '199',
 '1a',
 '1each',
 '1gb',
 '1ghz',
 '1m',
 '1mobil',
 '1of',
 '1st',
 '1thing',
 '1week',
 '1yo',
 '1yr',
 '20',
 '200',
 '2000',


In [20]:
# Create data frame
X = pd.DataFrame(bag_of_words.toarray(), columns=feature_names)
X

00  000  01  04  05  06  0ff  0ghz  0ne  10  ...    zigbe  zinio  zip  \
0       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
1       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
2       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
3       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
4       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
5       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
6       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
7       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
8       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
9       0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
10      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
11      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
12      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
13      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
14      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
15      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
16      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
17      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
18      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
19      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
20      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
21      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
22      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
23      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
24      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
25      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
26      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
27      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
28      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
29      0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
...    ..  ...  ..  ..  ..  ..  ...   ...  ...  ..  ...      ...    ...  ...   
34630   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34631   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34632   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34633   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34634   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34635   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34636   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34637   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34638   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34639   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34640   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34641   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34642   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34643   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34644   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34645   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34646   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34647   0    0   0   0   0   0    0     0    0   0  ...        0      0    0   
34648  

In [21]:
# *** Preparation for ML
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# default split is 75% for training and 25% for testing
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(25995, 9643)
(25995,)
(8665, 9643)
(8665,)


## <font color=00A99C> Linear Regression </font>

In [22]:

# Import the model:
#from sklearn.linear_model import LinearRegression

# Instantiate the model:
#lm = LinearRegression()

# Fit the model:
#lm.fit(X_train, y_train)

# Predict:
#y_pred = lm.predict(X_test)

# Take a look:
#y_pred


#### <font color=orange> Measurements </font>

In [23]:
# calculate MAE: Mean Absolute Error
#print(metrics.mean_absolute_error(y_test, y_pred))

In [24]:
# calculate MSE: Mean Square Error
#print(metrics.mean_squared_error(y_test, y_pred))

In [25]:
# calculate RMSE: Root Mean Squared Error
#print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

## <font color=00A99C> Logistic Regression </font>

In [26]:
# Import the model:
from sklearn.linear_model import LogisticRegression

# Instantiate the model:
logreg = LogisticRegression()

# Fit the model:
logreg.fit(X_train, y_train)

# Predict:
y_pred = logreg.predict(X_test)

# Take a look:
y_pred

/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([5., 5., 5., ..., 5., 5., 5.])

#### <font color=orange> Measurements </font>

In [27]:
print("Classification report for classifier %s:\n%s\n"
      % (logreg, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False):
              precision    recall  f1-score   support

         1.0       0.42      0.20      0.27       104
         2.0       0.30      0.08      0.12       105
         3.0       0.34      0.11      0.17       421
         4.0       0.49      0.27      0.35      2088
         5.0       0.76      0.93      0.83      5947

   micro avg       0.71      0.71      0.71      8665
   macro avg       0.46      0.32      0.35      8665
weighted avg       0.66      0.71      0.67      8665


Confusion matrix:
[[  21    4    9   17   53]
 [  12    8   18   29   38]
 [   8    6   48  145  214]
 [   3    6   51  564 1464]
 [   6    3   14  400 5524]]

Accuracy: 0.7114829774956722


## <font color=00A99C> Naive Bayes </font>

### <font color=00A99C> Gaussian Naive Bayes </font>

In [28]:
# Import the model:
from sklearn.naive_bayes import GaussianNB

# Instantiate the model:
nb = GaussianNB()

# Fit the model:
nb.fit(X_train, y_train)

# Predict:
y_pred = nb.predict(X_test)

# Take a look:
y_pred

array([5., 3., 1., ..., 4., 3., 3.])

#### <font color=orange> Measurements </font>

In [29]:
print("Classification report for classifier %s:\n%s\n"
      % (nb, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier GaussianNB(priors=None, var_smoothing=1e-09):
              precision    recall  f1-score   support

         1.0       0.01      0.13      0.02       104
         2.0       0.01      0.31      0.02       105
         3.0       0.06      0.20      0.09       421
         4.0       0.26      0.23      0.24      2088
         5.0       0.69      0.09      0.15      5947

   micro avg       0.13      0.13      0.13      8665
   macro avg       0.20      0.19      0.10      8665
weighted avg       0.54      0.13      0.17      8665


Confusion matrix:
[[  14   32   12   29   17]
 [   9   33   18   34   11]
 [  54  150   84   94   39]
 [ 284  788  366  484  166]
 [ 781 2375 1028 1251  512]]

Accuracy: 0.13006347374495095


### <font color=00A99C> Bernoulli Naive Bayes </font>

In [30]:
# Import the model:
from sklearn.naive_bayes import BernoulliNB

# Instantiate the model:
nb = BernoulliNB()

# Fit the model:
nb.fit(X_train, y_train)

# Predict:
y_pred = nb.predict(X_test)

# Take a look:
y_pred

array([2., 4., 5., ..., 3., 5., 5.])

#### <font color=orange> Measurements </font>

In [31]:
print("Classification report for classifier %s:\n%s\n"
      % (nb, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True):
              precision    recall  f1-score   support

         1.0       0.20      0.17      0.19       104
         2.0       0.05      0.01      0.02       105
         3.0       0.13      0.05      0.08       421
         4.0       0.43      0.27      0.33      2088
         5.0       0.76      0.89      0.82      5947

   micro avg       0.68      0.68      0.68      8665
   macro avg       0.31      0.28      0.29      8665
weighted avg       0.63      0.68      0.65      8665


Confusion matrix:
[[  18    0   17   27   42]
 [   4    1   17   52   31]
 [  11    0   23  178  209]
 [  16    6   57  569 1440]
 [  41   14   64  510 5318]]

Accuracy: 0.6842469705712637


### <font color=00A99C> Multinomial Naive Bayes </font>

In [32]:
# Import the model:
from sklearn.naive_bayes import MultinomialNB

# Instantiate the model:
nb = MultinomialNB()

# Fit the model:
nb.fit(X_train, y_train)

# Predict:
y_pred = nb.predict(X_test)

# Take a look:
y_pred

array([4., 4., 5., ..., 5., 5., 5.])

#### <font color=orange> Measurements </font>

In [33]:
print("Classification report for classifier %s:\n%s\n"
      % (nb, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True):
              precision    recall  f1-score   support

         1.0       0.41      0.11      0.17       104
         2.0       0.00      0.00      0.00       105
         3.0       0.31      0.05      0.09       421
         4.0       0.45      0.36      0.40      2088
         5.0       0.77      0.90      0.83      5947

   micro avg       0.71      0.71      0.71      8665
   macro avg       0.39      0.28      0.30      8665
weighted avg       0.66      0.71      0.67      8665


Confusion matrix:
[[  11    1    5   50   37]
 [   1    0   16   59   29]
 [   4    0   23  227  167]
 [   3    2   17  750 1316]
 [   8    4   14  594 5327]]

Accuracy: 0.7052510098095788


# <i>HELP!</i>

<b>WARNING!</b> Since the data is huge, in order to feed the following algorithms we needed to shrink the data: It takes too much time for algorithms to learn even on a GPU computer.

In [34]:
X = X[:5000]
y = y[:5000]

In [35]:
# *** Preparation for ML
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
# default split is 75% for training and 25% for testing
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(3750, 9643)
(3750,)
(1250, 9643)
(1250,)


## <font color=00A99C> SVM </font>

In [36]:
# Import the model:
from sklearn.svm import SVC

# Instantiate the model:
svm = SVC()

# Fit the model:
svm.fit(X_train, y_train)

# Predict:
y_pred = svm.predict(X_test)

# Take a look:
y_pred

/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


array([5., 5., 5., ..., 5., 5., 5.])

#### <font color=orange> Measurements </font>

In [37]:
print("Classification report for classifier %s:\n%s\n"
      % (svm, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False):
              precision    recall  f1-score   support

         1.0       0.00      0.00      0.00        30
         2.0       0.00      0.00      0.00        16
         3.0       0.00      0.00      0.00        53
         4.0       0.00      0.00      0.00       344
         5.0       0.65      1.00      0.78       807

   micro avg       0.65      0.65      0.65      1250
   macro avg       0.13      0.20      0.16      1250
weighted avg       0.42      0.65      0.51      1250


Confusion matrix:
[[  0   0   0   0  30]
 [  0   0   0   0  16]
 [  0   0   0   0  53]
 [  0   0   0   0 344]
 [  0   0   0   0 807]]

Accuracy: 0.6456


/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bilgi/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## <font color=00A99C> kNN </font>

In [38]:
# Import the model:
from sklearn.neighbors import KNeighborsClassifier

# Instantiate the model:
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the model:
knn.fit(X, y)

# Predict:
y_pred = knn.predict(X_test)

# Take a look:
y_pred

array([5., 5., 5., ..., 5., 5., 5.])

#### <font color=orange> Measurements </font>

In [39]:
print("Classification report for classifier %s:\n%s\n"
      % (knn, metrics.classification_report(y_test, y_pred)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

print()
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy: {}'.format(accuracy))

Classification report for classifier KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'):
              precision    recall  f1-score   support

         1.0       0.50      0.03      0.06        30
         2.0       0.57      0.25      0.35        16
         3.0       0.58      0.13      0.22        53
         4.0       0.62      0.26      0.37       344
         5.0       0.70      0.94      0.81       807

   micro avg       0.69      0.69      0.69      1250
   macro avg       0.60      0.32      0.36      1250
weighted avg       0.67      0.69      0.64      1250


Confusion matrix:
[[  1   0   0   3  26]
 [  0   4   0   2  10]
 [  1   0   7   9  36]
 [  0   1   3  90 250]
 [  0   2   2  41 762]]

Accuracy: 0.6912


## <font color=red> WordNET </font>

In [40]:
from nltk import word_tokenize, pos_tag
from nltk.corpus import wordnet as wn
import random

review_data = df['reviews_text'] #Seperate the comments
review_data

0        This product so far has not disappointed. My c...
1        great for beginner or experienced person. Boug...
2        Inexpensive tablet for him to use and learn on...
3        I've had my Fire HD 8 two weeks now and I love...
4        I bought this for my grand daughter when she c...
5        This amazon fire 8 inch tablet is the perfect ...
6        Great for e-reading on the go, nice and light ...
7        I gave this as a Christmas gift to my inlaws, ...
8        Great as a device to read books. I like that i...
9        I love ordering books and reading them with th...
10       Not easy for elderly users cease of ads that p...
11       Excellent product. Easy to use, large screen m...
12       Wanted my father to have his first tablet and ...
13       Simply does everything I need. Thank youAnd si...
14       Got it as a present and love the size of the s...
15       The kindle is easiest to use, graphics and scr...
16       nice reader. almost perfect for what i want/ne.

In [41]:
review_data_list = review_data.tolist()

In [42]:
def penn_to_wn(tag):
    """ Convert between a Penn Treebank tag to a simplified Wordnet tag """
    if tag.startswith('N'):
        return 'n'
 
    if tag.startswith('V'):
        return 'v'
 
    if tag.startswith('J'):
        return 'a'
 
    if tag.startswith('R'):
        return 'r'
 
    return None

In [43]:
def tagged_to_synset(word, tag):
    wn_tag = penn_to_wn(tag)
    if wn_tag is None:
        return None
 
    try:
        return wn.synsets(word, wn_tag)[0]
    except:
        return None

In [44]:
def sentence_similarity(sentence1, sentence2):
    """ compute the sentence similarity using Wordnet """
    # Tokenize and tag
    
    print("SENTENCE-1= ", sentence1)
    print()
    
    # Get the synsets for the tagged words
    sentence1 = nltk.pos_tag(word_tokenize(sentence1))
    print("TAGS OF SENTENCE-1= ", sentence1)
    print()
    
    synsets1 = [tagged_to_synset(*tagged_word) for tagged_word in sentence1]
    print("SYNSETS OF SENTENCE-1= ", synsets1)
    
    
    print("___")
    print()
    
    print("SENTENCE-2= ", sentence2)
    print()
    
    # Get the synsets for the tagged words
    sentence2 = nltk.pos_tag(word_tokenize(sentence2))
    print("TAGS OF SENTENCE-2= ", sentence2)
    print()
    
    synsets2 = [tagged_to_synset(*tagged_word) for tagged_word in sentence2]
    print("SYNSETS OF SENTENCE-2= ", synsets2)
    
    # Filter out the Nones
    synsets1 = [ss for ss in synsets1 if ss]
    synsets2 = [ss for ss in synsets2 if ss]
 
    score, count = 0.0, 0
    best_score = 0
    arr_simi_score = []
    for syn1 in synsets1:
        for syn2 in synsets2:
            simi_score = syn1.path_similarity(syn2)
            if simi_score is not None:
                arr_simi_score.append(simi_score)
                best_score = max(arr_simi_score)
        score += best_score
        count += 1
    
    # Average the values
    score /= count
    return score

In [45]:
sencentes_one = random.choice(review_data_list)
sencentes_two = random.choice(review_data_list)
#print("Sentence_one: [ {} ], \n\nSentence_two: [ {} ],\n\nSimilarity score:[ {} ] ".format(text_one, text_two, sentence_similarity(text_one, text_two)))
print("\n___\n\n\n-> Similarity score:[ {} ] ".format(sentence_similarity(sencentes_one, sencentes_two)))

SENTENCE-1=  i bought for my niece and really amazing and working very good.

TAGS OF SENTENCE-1=  [('i', 'NN'), ('bought', 'VBD'), ('for', 'IN'), ('my', 'PRP$'), ('niece', 'NN'), ('and', 'CC'), ('really', 'RB'), ('amazing', 'JJ'), ('and', 'CC'), ('working', 'JJ'), ('very', 'RB'), ('good', 'JJ'), ('.', '.')]

SYNSETS OF SENTENCE-1=  [Synset('iodine.n.01'), Synset('buy.v.01'), None, None, Synset('niece.n.01'), None, Synset('truly.r.01'), Synset('amazing.s.01'), None, Synset('working.s.01'), Synset('very.r.01'), Synset('good.a.01'), None]
___

SENTENCE-2=  A real nice tablet for children and got it on sale at Bestbuy

TAGS OF SENTENCE-2=  [('A', 'DT'), ('real', 'JJ'), ('nice', 'JJ'), ('tablet', 'NN'), ('for', 'IN'), ('children', 'NNS'), ('and', 'CC'), ('got', 'VBD'), ('it', 'PRP'), ('on', 'IN'), ('sale', 'NN'), ('at', 'IN'), ('Bestbuy', 'NNP')]

SYNSETS OF SENTENCE-2=  [None, Synset('real.a.01'), Synset('nice.a.01'), Synset('tablet.n.01'), None, Synset('child.n.01'), None, Synset('get.v.